import type { Metadata } from 'next'

import { Inter as FontSans } from "next/font/google"
import { Header } from '@/components/header'


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='flex min-h-screen flex-col antialiased'>
        <Header />

        <div className='flex flex-1 flex-col gap-4 p-8 pt-6'>
        {children}
        </div>
    </div>

  )
}